'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.Rdms.Charts

    Partial Public Class ByMonthHourly

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Chart1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Chart1 As Global.System.Web.UI.DataVisualization.Charting.Chart

        '''<summary>
        '''lblFace00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFaceTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaceTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChatTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChatTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhoneTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhoneTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocialTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocialTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessangerTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessangerTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVcTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVcTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOtherTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOtherTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour00 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour00 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour06 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour06 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour07 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour07 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour08 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour08 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour09 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour09 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHours As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PanelContentBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelContentBox As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''PanelSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelSubject As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblSubOd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubOd As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubDc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubDc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubIt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubIt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubOp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubOp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubLrc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubLrc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubRc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubRc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubFs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubFs As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubVp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubVp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubJa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubJa As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubGt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubGt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubEt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubEt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PanelEnquiry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelEnquiry As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblEnqQr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqQr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqRr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqRr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqSt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqSt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqAg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqAg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqEtc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqEtc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqTotal As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
