'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.Rdms.Charts

    Partial Public Class ByMonthWeekly

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Chart1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Chart1 As Global.System.Web.UI.DataVisualization.Charting.Chart

        '''<summary>
        '''lblFace01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFace05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFace05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFaceTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaceTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChat05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChat05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChatTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChatTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhoneTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhoneTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocial05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocial05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSocialTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSocialTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessanger05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessanger05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInMessangerTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInMessangerTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVc05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVc05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVcTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVcTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOther05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOther05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOtherTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOtherTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour01 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour01 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour02 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour02 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour03 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour03 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour04 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHour05 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHour05 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalHours As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PanelContentBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelContentBox As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''PanelSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelSubject As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblSubOd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubOd As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubDc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubDc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubIt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubIt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubOp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubOp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubLrc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubLrc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubRc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubRc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubFs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubFs As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubVp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubVp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubJa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubJa As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubGt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubGt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubEt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubEt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PanelEnquiry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelEnquiry As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblEnqQr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqQr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqRr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqRr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqSt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqSt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqAg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqAg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqEtc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqEtc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEnqTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnqTotal As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
