'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.Rdms.DutyCalendar.Monthly

    Partial Public Class Container

        '''<summary>
        '''Panel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnPrev1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPrev1 As Global.System.Web.UI.HtmlControls.HtmlButton

        '''<summary>
        '''lblMonthName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMonthName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblYear As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnNext1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNext1 As Global.System.Web.UI.HtmlControls.HtmlButton

        '''<summary>
        '''PlaceHolder1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder1 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder2 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder3 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder4 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder5 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder6 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder7 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder8 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder9 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder10 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder11 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder12 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder13 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder14 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder15 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder16 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder17 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder18 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder19 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder20 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder21 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder22 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder23 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder24 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder24 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder25 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder25 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder26 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder26 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder27 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder27 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder28 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder28 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder29 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder29 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder30 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder30 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder31 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder31 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder32 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder32 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder33 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder33 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder34 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder34 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PlaceHolder35 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder35 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phLegend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phLegend As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PanelDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelDebug As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gMonthNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gMonthNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gSatInit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gSatInit As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
