'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DashBoard

    '''<summary>
    '''PanelAnnouncement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAnnouncement As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Announcement1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Announcement1 As Global.Rdms_Metro.MyControls.Rdms.User.Dashboard.Panel.Announcement1

    '''<summary>
    '''upDutyChangeRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDutyChangeRequest As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''DutyChangeRequest1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DutyChangeRequest1 As Global.Rdms_Metro.MyControls.Rdms.User.Dashboard.Panel.DutyChangeRequest

    '''<summary>
    '''upNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upNotification As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Notification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Notification1 As Global.Rdms_Metro.Notification
End Class
