'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.MetroUI.FluentMenu.TabContentSegment

    Partial Public Class CheckinEnquiry

        '''<summary>
        '''enqQr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enqQr As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.EnquiryItem

        '''<summary>
        '''enqSt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enqSt As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.EnquiryItem

        '''<summary>
        '''enqRr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enqRr As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.EnquiryItem

        '''<summary>
        '''enqAg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enqAg As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.EnquiryItem

        '''<summary>
        '''enqEtc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enqEtc As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.EnquiryItem
    End Class
End Namespace
