'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.MetroUI.FluentMenu.TabContentSegment

    Partial Public Class CheckinSubject

        '''<summary>
        '''subOd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subOd As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subDc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subDc As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subIt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subIt As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subOp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subOp As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subLrc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subLrc As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subRc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subRc As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subFs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subFs As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subVp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subVp As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subJa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subJa As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subGt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subGt As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem

        '''<summary>
        '''subEtc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subEtc As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinItems.SubjectItem
    End Class
End Namespace
