'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.MetroUI.FluentMenu.TabContentSegment

    Partial Public Class SessionInfoEditor

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''btnReCalc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReCalc As Global.System.Web.UI.HtmlControls.HtmlButton

        '''<summary>
        '''txtTimeStart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeStart As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTimeStartExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeStartExt As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''txtTimeStartVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeStartVal As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''txtTimeStartReq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeStartReq As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ddStartHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStartHour As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStartMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStartMinute As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStartSecond control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStartSecond As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddEndHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddEndHour As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddEndMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddEndMinute As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddEndSecond control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddEndSecond As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDuration As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDurationMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDurationMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSessionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSessionId As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
