'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DutyAdd

    '''<summary>
    '''Breadcrumb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Breadcrumb1 As Global.Rdms_Metro.MyControls.MetroUI.Buttons.Breadcrumbs.Breadcrumb

    '''<summary>
    '''Staff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Staff As Global.Rdms_Metro.MyControls.Rdms.User.Staff

    '''<summary>
    '''phDutyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phDutyType As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''DutyTypeNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DutyTypeNotes As Global.Rdms_Metro.MyControls.Rdms.DutyCalendar.DutyTypeNotes
End Class
