'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserEditor

    '''<summary>
    '''Breadcrumb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Breadcrumb1 As Global.Rdms_Metro.MyControls.MetroUI.Buttons.Breadcrumbs.Breadcrumb

    '''<summary>
    '''UserEditor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserEditor1 As Global.Rdms_Metro.MyControls.Rdms.Admin.UserEditor
End Class
