'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.Rdms.Reports

    Partial Public Class YearlyOption

        '''<summary>
        '''a1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents a1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''ddYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddYear As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UpdatePanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ddListType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddListType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblFullname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFullname As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddBranch As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddSatellite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddSatellite As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddDepartment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddDepartment As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddDivision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddDivision As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddUnit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddUnit As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''chkType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkType As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ddFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStudBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStudBranch As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStudFaculty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStudFaculty As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStudProgram control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStudProgram As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStudCampus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStudCampus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStudLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStudLevel As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStudMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStudMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStafDepartment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStafDepartment As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddStafType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddStafType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CheckBox1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ddMedium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddMedium As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CheckBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''DropDownList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CheckBox3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''DropDownList2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownList2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''PanelHourlyDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelHourlyDisplay As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkHourDislplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHourDislplay As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''PanelDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelDisplay As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkPatron control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPatron As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkStudFaculty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStudFaculty As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkStudProgram control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStudProgram As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkStudCampus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStudCampus As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkStudLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStudLevel As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkStudMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStudMode As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkStafDept control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStafDept As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkStafType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStafType As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkCustom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCustom As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkOfficer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOfficer As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkBranch As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkSatellite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSatellite As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkDepartment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDepartment As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkDivision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDivision As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkUnit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUnit As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''PanelDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelDebug As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gSqlCommand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gSqlCommand As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gVirtualRedirectPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gVirtualRedirectPath As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gQueryString control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gQueryString As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
