'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.Rdms.Organization.SatelliteList

    Partial Public Class Item

        '''<summary>
        '''hlSatellite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlSatellite As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblSatelliteName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSatelliteName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PanelDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelDebug As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gSatelliteId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gSatelliteId As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
