'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.MetroUI.FluentMenu
    
    Partial Public Class Container
        
        '''<summary>
        '''CheckinInfo1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckinInfo1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabPanelGroup.CheckinInfo
        
        '''<summary>
        '''PatronInfo1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatronInfo1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabPanelGroup.PatronInfo
        
        '''<summary>
        '''Snippet1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Snippet1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabPanelGroup.Snippet
        
        '''<summary>
        '''SessionInfo1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SessionInfo1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SessionInfo
        
        '''<summary>
        '''OfficerInfo1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OfficerInfo1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabPanelGroup.OfficerInfo
        
        '''<summary>
        '''txtQuestion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQuestion As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtAnswer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnswer As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Panel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''btnKiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnKiv As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
