'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.Rdms.User.Dashboard.Panel

    Partial Public Class DutyChangeRequest

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PanelContentItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelContentItem As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''phDutyType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDutyType As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phRequestRec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phRequestRec As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PanelDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelDebug As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gPanelCollapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gPanelCollapse As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gPanelCollapseDisplayNone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gPanelCollapseDisplayNone As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
