'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.Rdms.Admin.UserSearchInternal

    Partial Public Class Container

        '''<summary>
        '''rfv1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfv1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''PanelMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelMain As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.HtmlControls.HtmlButton

        '''<summary>
        '''hiddenButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hiddenButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''lbOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbOption As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''PanelOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelOption As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rbPatronId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbPatronId As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbPassport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbPassport As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbName As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbAll As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''PanelLegend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelLegend As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResults As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phItem As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''PanelDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelDebug As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gVirtualPathRedirect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gVirtualPathRedirect As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gQueryString control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gQueryString As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
