'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default4

    '''<summary>
    '''DailyOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DailyOption As Global.Rdms_Metro.MyControls.Rdms.Reports.DailyOption

    '''<summary>
    '''ByMonthHourly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ByMonthHourly As Global.Rdms_Metro.MyControls.Rdms.Charts.ByMonthHourly

    '''<summary>
    '''ByMonthWeekly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ByMonthWeekly As Global.Rdms_Metro.MyControls.Rdms.Charts.ByMonthWeekly

    '''<summary>
    '''ByYearHourly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ByYearHourly As Global.Rdms_Metro.MyControls.Rdms.Charts.ByYearHourly

    '''<summary>
    '''ByYearMonthly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ByYearMonthly As Global.Rdms_Metro.MyControls.Rdms.Charts.ByYearMonthly
End Class
