'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.MetroUI.FluentMenu.TabPanelGroup

    Partial Public Class CheckinInfo

        '''<summary>
        '''PatronPhoto1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatronPhoto1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.PatronPhoto

        '''<summary>
        '''CheckinMedium1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckinMedium1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinMedium

        '''<summary>
        '''CheckinSubject1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckinSubject1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinSubject

        '''<summary>
        '''CheckinEnquiry1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckinEnquiry1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.CheckinEnquiry

        '''<summary>
        '''PanelDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelDebug As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gPatronId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gPatronId As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
