'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.MetroUI.FluentMenu.TabPanelGroup

    Partial Public Class PatronInfo

        '''<summary>
        '''PatronPhoto1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatronPhoto1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.PatronPhoto

        '''<summary>
        '''lblFullname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFullname As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLevel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPatronId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPatronId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFaculty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaculty As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProgram control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProgram As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCampus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCampus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PanelDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelDebug As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gStudFacultyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gStudFacultyCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gStudProgramCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gStudProgramCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gStudCampusCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gStudCampusCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gStudLevelCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gStudLevelCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gStudModeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gStudModeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gStafDeptCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gStafDeptCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gStafPosCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gStafPosCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gStafTypeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gStafTypeCode As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
