'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.MetroUI.FluentMenu.TabPanelGroup

    Partial Public Class QuickAccess

        '''<summary>
        '''Link control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link1 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link2 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link3 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link4 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link10 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link5 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link6 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link7 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link13 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link8 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link

        '''<summary>
        '''Link9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Link9 As Global.Rdms_Metro.MyControls.MetroUI.FluentMenu.TabContentSegment.SegmentItems.Link
    End Class
End Namespace
