'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MyControls.MetroUI.FluentMenu.TabPanelGroup

    Partial Public Class Snippet

        '''<summary>
        '''ddQuestion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddQuestion As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddAnswer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddAnswer As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
